from requests.get.get_body_weight import get_body_weight
from requests.get.get_workout import get_workout
from requests.put.put_workout import put_workout
from requests.put.put_body_weight import put_body_weight
from data_manager.body_weight_data import *
from data_manager.workout_data import *
from utils.get_evolution import get_evolution
from utils.get_median import get_median
from utils.get_average import get_average